name: ✨ Feature request
description: Suggest an idea or enhancement
title: "Feature: <short description>"
labels: ["type/feature", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe the problem and what success looks like.

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What user pain or business goal does this solve?
      placeholder: "As a ..., I want ..., so that ..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What do you want to happen? Keep it high-level if needed.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered?
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of testable outcomes.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: non_goals
    attributes:
      label: Non-goals / out of scope
      placeholder: |
        - ...
    validations:
      required: false

  - type: textarea
    id: ux_notes
    attributes:
      label: UX / API notes (optional)
      description: Mockups, flows, API examples, screenshots, links.
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / risks
      description: Other teams, constraints, security/compliance, migrations, performance, etc.
    validations:
      required: false

  - type: input
    id: success_metrics
    attributes:
      label: Success metrics (optional)
      description: How should we measure success?
      placeholder: "e.g., reduce time-to-complete by 20%"
    validations:
      required: false

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      options:
        - label: I searched existing issues and didn’t find a duplicate.
          required: true
