name: ✅ Task
description: A scoped unit of work with a clear outcome
title: "Task: <short description>"
labels: ["type/task", "needs-triage"]
assignees: []
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What is the outcome we want?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Background, links, related issues/PRs.
    validations:
      required: false

  - type: textarea
    id: done
    attributes:
      label: Definition of done
      description: Clear, testable completion criteria.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Urgent
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: false
